version: "3.9"
services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asif12345
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
  api:
    build:
      context: .
    container_name: fastapi_blog
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:asif12345@postgres_db:5432/blogdb
